apiVersion: v1
kind: ConfigMap
metadata:
  name: horses-prometheus-server-conf
  labels:
    name: horses-prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'horses'
        scrape_interval: 5s
        metrics_path: /api/metrics
        scheme: http

        static_configs:
        - targets: ['horses:8091']
