/*
 * Betfair: Exchange Streaming API
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.betfair.esa.swagger.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * KeyLineDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-07T12:34:48.137476+03:00[Europe/Riga]")
public class KeyLineDefinition {
  @SerializedName("kl")
  private List<KeyLineSelection> kl = null;

  public KeyLineDefinition kl(List<KeyLineSelection> kl) {
    this.kl = kl;
    return this;
  }

  public KeyLineDefinition addKlItem(KeyLineSelection klItem) {
    if (this.kl == null) {
      this.kl = new ArrayList<KeyLineSelection>();
    }
    this.kl.add(klItem);
    return this;
  }

   /**
   * Get kl
   * @return kl
  **/
  @Schema(description = "")
  public List<KeyLineSelection> getKl() {
    return kl;
  }

  public void setKl(List<KeyLineSelection> kl) {
    this.kl = kl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyLineDefinition keyLineDefinition = (KeyLineDefinition) o;
    return Objects.equals(this.kl, keyLineDefinition.kl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyLineDefinition {\n");
    
    sb.append("    kl: ").append(toIndentedString(kl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
