/*
 * Betfair: Exchange Streaming API
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.betfair.esa.swagger.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * MarketDataFilter
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-07T12:34:48.137476+03:00[Europe/Riga]")
public class MarketDataFilter {
  @SerializedName("ladderLevels")
  private Integer ladderLevels = null;

  /**
   * Gets or Sets fields
   */
  @JsonAdapter(FieldsEnum.Adapter.class)
  public enum FieldsEnum {
    EX_BEST_OFFERS_DISP("EX_BEST_OFFERS_DISP"),
    EX_BEST_OFFERS("EX_BEST_OFFERS"),
    EX_ALL_OFFERS("EX_ALL_OFFERS"),
    EX_TRADED("EX_TRADED"),
    EX_TRADED_VOL("EX_TRADED_VOL"),
    EX_LTP("EX_LTP"),
    EX_MARKET_DEF("EX_MARKET_DEF"),
    SP_TRADED("SP_TRADED"),
    SP_PROJECTED("SP_PROJECTED");

    private String value;

    FieldsEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static FieldsEnum fromValue(String text) {
      for (FieldsEnum b : FieldsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<FieldsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FieldsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FieldsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FieldsEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("fields")
  private List<FieldsEnum> fields = null;

  public MarketDataFilter ladderLevels(Integer ladderLevels) {
    this.ladderLevels = ladderLevels;
    return this;
  }

   /**
   * Get ladderLevels
   * @return ladderLevels
  **/
  @Schema(description = "")
  public Integer getLadderLevels() {
    return ladderLevels;
  }

  public void setLadderLevels(Integer ladderLevels) {
    this.ladderLevels = ladderLevels;
  }

  public MarketDataFilter fields(List<FieldsEnum> fields) {
    this.fields = fields;
    return this;
  }

  public MarketDataFilter addFieldsItem(FieldsEnum fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<FieldsEnum>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @Schema(description = "")
  public List<FieldsEnum> getFields() {
    return fields;
  }

  public void setFields(List<FieldsEnum> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketDataFilter marketDataFilter = (MarketDataFilter) o;
    return Objects.equals(this.ladderLevels, marketDataFilter.ladderLevels) &&
        Objects.equals(this.fields, marketDataFilter.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ladderLevels, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketDataFilter {\n");
    
    sb.append("    ladderLevels: ").append(toIndentedString(ladderLevels)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
