apiVersion: v1
kind: ConfigMap
metadata:
  name: horses-grafana-ini
  labels:
    name: horses-grafana-ini
data:
  grafana.ini: |-
    [auth.anonymous]
      enabled = true
      org_name = Public
      org_role = Viewer
      hide_version = true
